# ===============================
# = APPLICATION CONFIG
# ===============================
spring.application.name=Bank-Account-Management-System

# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# = DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/bank_db
spring.datasource.username=root
spring.datasource.password=E23shastrinagar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# = SPRING DATA REST CONFIG \uD83D\uDD25
# ===============================
spring.data.rest.base-path=/api
